health_keywords = ["health", "medicine", "doctor", "symptoms", "treatment", "prescription", "wellness", "medical advice",
                       "disease", "illness", "condition", "ailment", "infection", "fever", "cough", "headache",
                       "nausea", "vomiting", "diarrhea", "fatigue", "remedy", "cure", "prevention",
                       "diagnosis", "prognosis", "consultation", "medical history", "immunization", "vaccine",
                       "pharmacy", "pharmaceuticals", "side effects", "dosage", "medicine cabinet",
                       "healthcare provider", "general practitioner", "specialist", "nurse", "physician assistant",
                       "hospital", "clinic", "emergency room", "operating room", "ICU", "intensive care unit",
                       "primary care", "secondary care", "tertiary care", "quarantine", "isolation",
                       "health insurance", "coverage", "premium", "policy", "benefits", "claim",
                       "medical record", "electronic health record", "HIPAA", "patient confidentiality",
                       "medical research", "clinical trial", "medical journal", "peer-reviewed",
                       "public health", "epidemiology", "outbreak", "pandemic", "contagious", "transmission",
                       "immunity", "herd immunity", "hygiene", "sanitation", "nutrition", "diet", "exercise",
                       "fitness", "mental health", "stress", "anxiety", "depression", "therapy", "counseling",
                       "substance abuse", "addiction", "rehabilitation", "well-being", "holistic health",
                       "alternative medicine", "integrative medicine", "complementary medicine",
                       "traditional medicine", "naturopathy", "acupuncture", "homeopathy", "chiropractic",
                       "osteopathy", "massage therapy", "aromatherapy", "herbal medicine", "supplements",
                       "vitamins", "minerals", "nutritional supplements", "dietary supplements",
                       "nutraceuticals", "functional foods", "superfoods", "organic foods",
                       "genetic predisposition", "hereditary", "genetic testing", "DNA", "genomics",
                       "genome sequencing", "gene therapy", "stem cells", "regenerative medicine",
                       "precision medicine", "personalized medicine", "telemedicine", "virtual care",
                       "wearable technology", "health monitoring", "health tracking", "fitness tracker",
                       "smartwatch", "mobile health apps", "mHealth", "telehealth", "remote patient monitoring",
                       "anemia", "asthma", "arthritis", "diabetes", "hypertension", "hyperthyroidism",
                       "hypothyroidism", "migraine", "osteoporosis", "pneumonia", "stroke", "tuberculosis",
                       "coronary artery disease", "fibromyalgia", "chronic obstructive pulmonary disease",
                       "endometriosis", "gastroesophageal reflux disease", "irritable bowel syndrome",
                       "multiple sclerosis", "Parkinson's disease", "Alzheimer's disease", "schizophrenia",
                       "bipolar disorder", "post-traumatic stress disorder", "cancer", "leukemia", "lymphoma",
                       "melanoma", "breast cancer", "colon cancer", "lung cancer", "prostate cancer",
                       "skin cancer", "heart attack", "cardiac arrest", "arrhythmia", "congestive heart failure",
                       "kidney stones", "urinary tract infection", "gastroenteritis", "appendicitis",
                       "concussion", "fracture", "sprain", "strain", "pneumothorax", "hypoglycemia",
                       "hyperglycemia", "anaphylaxis", "sepsis", "hypotension", "hypertension",
                       "pulmonary embolism", "deep vein thrombosis", "cirrhosis", "hepatitis", "pancreatitis",
                       "diverticulitis", "gastritis", "peptic ulcer disease", "celiac disease", "Crohn's disease",
                       "ulcerative colitis", "gout", "rheumatoid arthritis", "lupus", "psoriasis",
                       "eczema", "acne", "rosacea", "warts", "genital herpes", "gonorrhea", "syphilis",
                       "chlamydia", "HIV", "AIDS", "influenza", "common cold", "bronchitis", "sinusitis",
                       "tonsillitis", "pharyngitis", "otitis media", "conjunctivitis", "glaucoma",
                       "cataracts", "macular degeneration", "amblyopia", "strabismus", "myopia", "hyperopia",
                       "astigmatism", "presbyopia", "cataract surgery", "LASIK", "contact lenses",
                       "orthokeratology", "retinal detachment", "retinopathy", "macular edema",
                       "keratoconus", "uveitis", "iritis", "keratitis", "corneal ulcer", "conjunctival hemorrhage",
                       "corneal abrasion", "retinal vein occlusion", "retinal artery occlusion",
                       "central retinal vein occlusion", "central retinal artery occlusion", "retinal tear",
                       "retinal detachment", "macular hole", "macular pucker", "epiretinal membrane",
                       "diabetic retinopathy", "hypertensive retinopathy", "retinal degeneration",
                       "retinal detachment", "retinitis pigmentosa", "macular degeneration",
                       "optic neuritis", "optic neuropathy", "glaucoma", "uveitis", "iritis", "retinal detachment",
                       "keratoconus", "corneal dystrophy", "corneal ulcer", "conjunctivitis", "blepharitis",
                       "chalazion", "stye", "papilledema", "conjunctival cyst", "conjunctival tumor",
                       "corneal abrasion", "corneal foreign body", "corneal perforation", "corneal ulcer",
                       "eye pain", "blurry vision", "double vision", "flashes of light", "floaters",
                       "redness", "itchiness", "tearing", "burning sensation", "foreign body sensation",
                       "sensitivity to light", "bulging eye", "sunken eye", "abnormal eye movement",
                       "watery eye", "dry eye", "swelling", "lump or mass", "discharge", "crusting",
                       "drooping eyelid", "crossed eyes", "lazy eye", "loss of vision", "changes in vision",
                       "glaucoma", "cataracts", "macular degeneration", "diabetic retinopathy",
                       "retinal detachment", "eye injury", "trauma to the eye", "blow to the eye",
                       "foreign object in the eye", "chemical burn to the eye", "eye infection",
                       "conjunctivitis", "corneal ulcer", "keratitis", "uveitis", "iritis", "endophthalmitis",
                       "retinal vein occlusion", "retinal artery occlusion", "optic neuritis", "optic neuropathy",
                       "papilledema", "papillitis", "optic nerve atrophy", "optic nerve compression",
                       "optic nerve tumor", "optic glioma", "orbital cellulitis", "orbital tumor",
                       "orbital fracture", "eyelid laceration", "eye tumor", "eye cancer", "eye melanoma",
                       "eye lymphoma", "choroidal melanoma", "retinoblastoma", "eye stroke", "visual snow",
                       "ocular migraine", "ocular histoplasmosis", "ocular toxoplasmosis", "ocular syphilis",
                       "ocular tuberculosis", "ocular sarcoidosis", "ocular herpes", "ocular shingles",
                       "ocular pemphigoid", "ocular cicatricial pemphigoid", "ocular graft-versus-host disease",
                       "ocular surface disease", "ocular rosacea", "ocular allergies", "ocular surface tumor",
                       "ocular surface cancer", "ocular surface melanoma", "ocular surface lymphoma",
                       "ocular surface squamous neoplasia", "ocular surface carcinoma", "uveitis",
                       "anterior uveitis", "posterior uveitis", "intermediate uveitis", "panuveitis",
                       "scleritis", "episcleritis", "iridocyclitis", "iriditis", "choroiditis", "chorioretinitis",
                       "pars planitis", "vogt-koyanagi-harada syndrome", "sympathetic ophthalmia",
                       "birdshot chorioretinopathy", "retinitis", "retinal vasculitis", "serpiginous choroiditis",
                       "necrotizing retinitis", "herpetic retinitis", "cytomegalovirus retinitis", "toxoplasma retinitis",
                       "acute retinal necrosis", "fungal retinitis", "parasitic retinitis", "interstitial keratitis",
                       "neuroretinitis", "retinal artery occlusion", "central retinal artery occlusion",
                       "branch retinal artery occlusion", "retinal vein occlusion", "central retinal vein occlusion",
                       "branch retinal vein occlusion", "macular edema", "macular hole", "macular pucker",
                       "epiretinal membrane", "macular degeneration", "wet macular degeneration", "dry macular degeneration",
                       "geographic atrophy", "macular ischemia", "central serous chorioretinopathy", "submacular hemorrhage",
                       "subretinal hemorrhage", "choroidal neovascularization", "angioid streaks",
                       "drusen", "retinal pigment epithelial detachment", "choroidal detachment", "vitreous hemorrhage",
                       "vitreous detachment", "vitreomacular traction", "retinoschisis", "retinal detachment",
                       "rhegmatogenous retinal detachment", "tractional retinal detachment", "exudative retinal detachment",
                       "familial exudative vitreoretinopathy", "retinal tear", "retinal break", "macular tear",
                       "retinal dialysis", "retinal hole", "retinal avulsion", "retinal detachment with giant tear",
                       "posterior vitreous detachment", "posterior vitreous detachment with retinal tear",
                       "retinal detachment with proliferative vitreoretinopathy", "macular retinoschisis",
                       "vitreous hemorrhage", "subretinal hemorrhage", "intraretinal hemorrhage",
                       "retinal hemorrhage", "choroidal hemorrhage", "hyphema", "vitreal hemorrhage",
                       "vitreous floaters", "retinal pigment epithelial detachment", "macular hemorrhage",
                       "macular neovascularization", "choroidal neovascularization", "angioid streaks",
                       "punctate inner choroidopathy", "multifocal choroiditis", "ocular histoplasmosis syndrome",
                       "presumed ocular histoplasmosis syndrome", "myopic choroidal neovascularization",
                       "pathologic myopia", "malignant myopia", "posterior staphyloma", "macular hole",
                       "macular pseudohole", "macular lamellar hole", "full-thickness macular hole",
                       "lamellar macular hole", "myopic macular hole", "idiopathic macular hole",
                       "secondary macular hole", "traumatic macular hole", "macular cyst", "macular edema",
                       "cystoid macular edema", "diffuse macular edema", "macular cystoid edema",
                       "cystoid macular edema", "macular telangiectasia", "macular retinal telangiectasia",
                       "macular capillary telangiectasia", "juxtafoveal telangiectasia", "paramacular telangiectasia",
                       "perifoveal telangiectasia", "perifoveal telangiectasia", "perifoveal retinal telangiectasia",
                       "perifoveal capillary telangiectasia", "retinal telangiectasia", "retinal capillary telangiectasia",
                       "macular pucker", "macular epiretinal membrane", "idiopathic macular pucker",
                       "secondary macular pucker", "traumatic macular pucker", "epiretinal membrane",
                       "macular cyst", "macular pseudocyst", "macular schisis", "macular schisis with detachment",
                       "myopic macular schisis", "idiopathic macular schisis", "secondary macular schisis",
                       "traumatic macular schisis", "familial exudative vitreoretinopathy", "Coats' disease",
                       "retinopathy of prematurity", "retinal dystrophy", "retinitis pigmentosa",
                       "Leber's congenital amaurosis", "Stargardt disease", "choroideremia", "gyrate atrophy",
                       "achromatopsia", "cone dystrophy", "cone-rod dystrophy", "cone-rod retinal dystrophy",
                       "rod-cone dystrophy", "rod-cone retinal dystrophy", "night blindness",
                       "nyctalopia", "tunnel vision", "peripheral vision loss", "color vision deficiency",
                       "color blindness", "red-green color blindness", "blue-yellow color", "headache", "cancer" ]


def checking(query):
    flag = False
    list_of_words = query.split(" ")
    for i in list_of_words:
        if i.lower() in health_keywords:
            flag = True
            break
    return flag


# if checking("i have an headache"):
#     print("sucess")
# else:
#     print("failed")

